version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    kiota-dependencies:
      patterns:
        - "*kiota*"
- package-ecosystem: gradle
  directory: "/android"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    kiota-dependencies:
      patterns:
        - "*kiota*"
- package-ecosystem: gradle
  directory: "/samples/deviceCodeSample"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/samples/interactiveBrowserSample"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    kiota-dependencies:
      patterns:
        - "*kiota*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    kiota-dependencies:
      patterns:
        - "*kiota*"
- package-ecosystem: gradle
  directory: "/android"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    kiota-dependencies:
      patterns:
        - "*kiota*"
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    kiota-dependencies:
      patterns:
        - "*kiota*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
