name: "samples build check"

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.java'
      - '**/*.yml'

jobs:
  samples-build-check-device-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 20
    - name: Add execution right to the script
      run: chmod +x gradlew
      working-directory: ./samples/deviceCodeSample
    - name: Build and run type summary project
      run: ./gradlew --no-daemon build
      working-directory: ./samples/deviceCodeSample
  samples-build-check-interactive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 20
    - name: Add execution right to the script
      run: chmod +x gradlew
      working-directory: ./samples/interactiveBrowserSample
    - name: Build and run type summary project
      run: ./gradlew --no-daemon build
      working-directory: ./samples/interactiveBrowserSample